### ISSUE TITLE
Manual Entry Issues

### ISSUE THREAD

**Issue by TheBig-O** [jovandeginste/workout-tracker#217]
When I enter a run manually, there are two issues that make it difficult and on result I am not sure about.

- When I attempt to enter a total time for the run, the input box asks for AM or PM. Although I get that time inputs typically go in 24 hour increments, it may be helpful if this is adjusted to allow 24hour type entries so that there is no AM/PM. Also, the time entry does not allow for seconds to be accounted.
- The second issue is the distance entry. When I attempt to enter a decimal number, it shows an error that requests a whole number.
- The final issue is something I don't understand enough to guess at. If I do enter a whole number in the distance field, saving it results in a seemingly random distance on the dashboard and in the workout editor.
 
None of these are show stoppers as I rarely have manually entered workouts, but I did want to let you know about htem.
Cheers!

<img width="520" alt="image" src="https://github.com/user-attachments/assets/2ac66a0e-012f-4c90-8774-8347f206231b">

**Comment by jovandeginste** [comment]
Thanks for reporting this. I'll admit I didn't test the new manual add/edit form with Imperial units enabled...

(The seemingly random distance issue, is because the database stores distances in meters, and the application converts the unit as needed; I forgot to convert the input from miles to meters before storing it, but did convert from meters to miles when showing)

All the issues should be addressed in the linked PR; if you find any other, don't hesitate to report!

**Comment by TheBig-O** [comment]
You're awesome. I really appreciate the quick work you're doing and am glad you're not ticked off about my constant issues!
Thanks for that and all your hard work!!!
