### ISSUE TITLE
Feature request: Burnt calories

### ISSUE THREAD

**Issue by repomaa** [jovandeginste/workout-tracker#260]
I think it would be nice if workout-tracker could give you an estimate of calories burnt. I think it should also be clear to the user how they are calculated. Excess vs. total, METs, whatever. Just a thought. :)

**Comment by jovandeginste** [comment]
It sounds nice, but a quick search tells me I need to record the age, gender (both doable, because this can be stored in the user's profile) and weight at that moment (this is an issue, because it varies every time, and varies greatly across the years.

We can not let the user store their weight as a single value in their profile and update it when it changes, because then all previous workouts will show a different estimate than before; so basically, I would need to add a sequence of weight measurements (weight tracking), with ability to remove erroneous values, etc... 

So, nice idea, and I would like to add it, but won't be a quick addition ...

**Comment by jovandeginste** [comment]
I added a rough estimate now to the workout details; please let me know if you think it should be altered. It's also limited to a number of workout types, but more can be added (I added some references with numbers, where I got them from etc.)

**Comment by repomaa** [comment]
@jovandeginste nice! this is already much better than nothing! Would it be possible to add the weight (and optionally gender?) as params for the profile? I think it would not be necessary to store historic data about weight (although that would also have it's benefits) but the METs could be calculated for each workout based on the current weight and stored as such instead of being calculated on the fly. What do you think?

**Comment by jovandeginste** [comment]
I was thinking about this; the gender seems easy (or easier - it tends not to change very often); perhaps the same is true for the weight: though it varies a lot, the amount with which it varies does not affect the calories burnt that much...

**Comment by repomaa** [comment]
@jovandeginste yes, but if you calculate it once, when the workout is added, you don't need to store historic data of weight or gender. Example:

I add a new workout. At this point I have set my weight to 88 kg and my gender as male. Now we calculate the burnt calories based on these values and store the calculated value in the db with our workout. Two weeks later I change my weight to 86 kg. From this point on forwards all future workouts are calculated with the updated weight while leaving the past workouts unchanged.

Do you know what I mean?

**Comment by jovandeginste** [comment]
@repomaa I added a new feature, which should cover this...
