### ISSUE TITLE
Issue with GPX exported from Workoutdoors

### ISSUE THREAD

**Issue by pixelspark** [jovandeginste/workout-tracker#4]
Great project!

When importing a GPX generated by the Workoutdoors iOS app, I get this error: `constraint failed: NOT NULL constraint failed: workouts.date (1299)`. 

Importing a GPX generated by Strava from the same workout works. The difference appears to be that the Workoutdoors file does not have a `<time>` element under `<metadata>` in the GPX, whereas the Strava one has it. The Workoutdoors file does have `<time>` items under each track point:

````xml
<gpx version="1.1" ...>
<metadata><name>Wednesday Evening Run</name></metadata>
<trk><name>Wednesday Evening Run</name><type>running</type>
<trkseg>
<trkpt lat="xxx" lon="xxx">
<ele>-30</ele><time>2024-02-28T17:26:34.000Z</time>
````

Perhaps the importer could use the earliest date in the file in case a date under metadata is missing.

I can have a go at implementing this myself if such feature would be desirable. If so any guidance on where to start would be appreciated (i.e. which part of the code to look)!

**Comment by jovandeginste** [comment]
I'll be verbose - skip as you please :)

The error comes from [this line](https://github.com/jovandeginste/workout-tracker/blob/master/pkg/database/workouts.go#L17):

```golang
type Workout struct {
	[...]
	Date     *time.Time `gorm:"not null"`
	[...]
}
```

The `Date` field is indeed mandatory. It is set [at this point](https://github.com/jovandeginste/workout-tracker/blob/master/pkg/database/workouts.go#L55) when parsing a new file:

```golang
	w := Workout{
		[...]
		Name:     gpxName(gpxContent),
		[...]
		Date:     gpxContent.Time,
		[...]
	}
```

I left the `Name` line too, because this would be the way I would fix it:
- create a new function `gpxTime` in `workouts_map.go`, similar to [`gpxName`](https://github.com/jovandeginste/workout-tracker/blob/master/pkg/database/workouts_map.go#L126-L136)
- iterate through some possible fields
  - start with `gpxContent.Time`
  - if that's empty, try the first point of the first segment of the first track

Can you work with this? Thanks in advance! If it works with some tools, feel free to create a PR to the README compatibility section!

**Comment by pixelspark** [comment]
Thanks for the elaborate explanation, will have a look this weekend! (Also: groeten uit Nederland :-))
